version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:22.12.0
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run: npm test

  build:
    docker:
      - image: circleci/node:22.12.0
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
      - run: npm ci
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    docker:
      - image: circleci/node:22.12.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploying the app
          command: |
            echo "Deploying to production..."
            # Add deployment commands here (e.g., AWS, Firebase, Heroku, etc.)

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
