version: 2.1

jobs:

  build:
    docker:
      - image: node:18-alpine
    steps:
      - checkout
      - run: npm install

  test:
    docker:
      - image: node:18-alpine
    steps:
      - checkout
      - run: npm install
      - run: npm test

  deploy:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t 0xzainraza/myapp:latest .
            docker push 0xzainraza/myapp:latest
      - run:
          name: Deploying the app
          command: |
            echo "Deploying to production..."
            # Add deployment commands here (e.g., AWS, Firebase, Heroku, etc.)

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
