version: 2.1

jobs:

  build:
    docker:
      - image: node:18-alpine
    steps:
      - checkout
      - run: npm install

  test:
    docker:
      - image: node:18-alpine
    steps:
      - checkout
      - run: npm install
      - run: npm test

  deploy:
    docker:
      - image: node:18-alpine
    steps:
      - checkout
      - run:
          name: Deploying the app
          command: |
            echo "Deploying to production..."
            # Add deployment commands here (e.g., AWS, Firebase, Heroku, etc.)

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
