version: 2.1

orbs:
  email: cinotify/email@1.2.1

executors:
  node-executor:
    docker:
      - image: node:18-alpine
  docker-executor:
    docker:
      - image: circleci/python:3.9  # Or any appropriate Docker image

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm install

  test:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm test | tee test-results.txt
      - store_artifacts:
          path: test-results.txt  # Store test logs

  sonar_scan:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: SonarQube Analysis
          command: |
            echo "Sonar Scanner"

  dependency_check:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Java and Dependency-Check
          command: |
            apk add --no-cache openjdk11 wget unzip
            export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
            mkdir -p reports
            wget https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.1/dependency-check-12.1.1-release.zip
            unzip dependency-check-12.1.1-release.zip -d dependency-check
            ./dependency-check/dependency-check/bin/dependency-check.sh --scan ./ --format HTML --out reports/dependency-report.html --nvdApiKey $NVD_API_KEY

      - store_artifacts:
          path: reports/dependency-report.html

  deploy:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t 0xzainraza/myapp:latest .
            docker push 0xzainraza/myapp:latest

  send_email_reports:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Send Email with Attachments
          command: |
            curl -X POST https://api.mailgun.net/v3/yourdomain.com/messages \
            -F from="you@yourdomain.com" \
            -F to="K214755@gmail.com" \
            -F subject="CircleCI Reports" \
            -F text="Please find the attached SonarQube, Dependency-Check, and Test reports." \
            -F attachment=@test-results.txt \
            -F attachment=@reports/dependency-report.html \
            -u "api:$MAILGUN_API_KEY"

workflows:
  ci_pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - sonar_scan:
          requires:
            - test
      - dependency_check:
          requires:
            - test
      - deploy:
          requires:
            - sonar_scan
            - dependency_check
      - send_email_reports:
          requires:
            - deploy
